name: "Gradle build"
permissions: {}
on:
  - pull_request
  - workflow_dispatch

jobs:
  build:
    name: "Gradle build"
    runs-on: ubuntu-latest
    env:
      GRADLE_MICROG_VERSION_WITHOUT_GIT: 1

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: "Setup matchers"
        run: |
          # Setting up matchers...

          matchers_dir='${{ github.workspace }}/.github/matchers'
          matcher_list()
          {
            echo 'gradle-build-matcher.json'
            echo 'gradle-build-kotlin-error-matcher.json'
          }

          matcher_list | while IFS='' read -r NAME; do
            if test -f "${matchers_dir:?}/${NAME:?}"; then
              echo "::add-matcher::${matchers_dir:?}/${NAME:?}"
              echo "Matcher configured: ${NAME:?}"
            fi
          done
      - name: "Execute Gradle assemble"
        run: "./gradlew assembleVtmDefaultDebugArm64-v8a"
        
      - name: "Upload a Build Artifact"
        uses: actions/upload-artifact@v4.6.0
        with:
          name: "microg-release"
          path: play-services-core/build/outputs/apk/vtmDefault/debug/
  
